---
- name: PlayBook Maestro - Prestamo temporal del password de root
  hosts: localhost
  gather_facts: false
#  strategy: serial

  tasks:
    - include_role:
        name: role_prestamo_root_temporal
