---
- block:
    - name: Crear copia de respaldo de bp.conf
      copy:
        src: "{{ nbfbpconf }}"
        dest: "{{ nbfbpconf }}.bak_{{ ansible_date_time.date }}_{{ ansible_date_time.epoch }}"
        remote_src: true
        mode: '0644'

    # - name: Eliminar cualquier linea que contenga los hostnames de NetBackup
    #   lineinfile:
    #     path: "{{ filehosts }}"
    #     regexp: '^.*?\b(vxnbucfs|cpdnbumedia3-le|lvprpbckrescc01-cfs)\b.*$'
    #     state: absent
  become: true