---
- block:
    - name: Cuarta condición, validar archivo o comando versión NetBackup
      set_fact:
        run_playbook: |
          {% if applies_certs %}
          ['s13nbcommclnch','s14nbcommcrttknms','s15nbcommcrttkncl','s13nbcommclnch','s16nbcommself','s17nbcommpn','s18chknbselfpn']
          {% else %}
          ['s13nbcommclnch','s16nbcommself','s17nbcommpn','s18chknbselfpn']
          {% endif %}
    
    - name: Ejecutar tareas NetBackup
      include_tasks: "{{ asbpbact4 }}.yml"
      loop: "{{ run_playbook | from_yaml }}"
      loop_control:
        loop_var: asbpbact4
      when: hostvars[inventory_hostname].get('cfs_status', 'OK') != 'ERROR'
