---
- block:
    - name: Validar resolución de nombre del cliente (bpclntcmd -self)
      shell: /usr/openv/netbackup/bin/netbackup_emulator.sh bpclntcmd -self
      register: bpclntcmd_self
      args:
        chdir: "{{ nbbin }}"
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/openv/netbackup/bin:{{ ansible_env.PATH }}"
      changed_when: false
      failed_when: false
  become: true