---
- block:
    - name: Validar comunicación con Master Server (bpclntcmd -pn)
      shell: /usr/openv/netbackup/bin/netbackup_emulator.sh bpclntcmd -pn
      register: bpclntcmd_pn
      args:
        chdir: "{{ nbbin }}"
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/openv/netbackup/bin:{{ ansible_env.PATH }}"
      changed_when: false
      failed_when: false
  become: true