---
- block:
    - name: Verificar si existe le archivo versión NetBackup
      stat:
        path: "{{ nbfile }}"
      register: nbu_file

    - name: Primera condición, validar archivo o comando versión NetBackup
      set_fact:
        run_playbook: |
          {% if nbu_file.stat.exists %}
          ['s2getnbfileversion','s6chkiprobotica']
          {% else %}
          ['s3chknbcomm']
          {% endif %}
    
    - name: Ejecutar tareas NetBackup en base a condiciones
      include_tasks: "{{ asbpbact1 }}.yml"
      loop: "{{ run_playbook | from_yaml }}"
      loop_control:
        loop_var: asbpbact1
      when: hostvars[inventory_hostname].get('cfs_status', 'OK') != 'ERROR'

#,'s7bckfilehosts','s8prgfilehosts','s9addnbmscipsrbfilehosts'