---
- block:
    - name: Leer versión del cliente NetBackup
      shell: "cat version | {{ nbparamfv }}"
      register: nbchkrfv
      args:
        chdir: "{{ nbbin }}"
      changed_when: false

    - name: Formatear versión de NetBackup
      set_fact:
        nbversion: "{{ nbchkrfv.stdout | trim }}"
#        nbcversion: "{{ nbchkfv.stdout | regex_search('([0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+|[0-9]+\\.[0-9]+\\.[0-9]+)') }}"

    - name: Evaluar si requiere gestión de certificados (Versión >= 8.0)
      set_fact:
        applies_certs: "{{ nbversion is version('8.0', '>=') }}"
  