---
- block:
    - name: Registrar error de prerrequisitos NetBackup (Comando y Version)
      set_fact:
        cfs_status: 'ERROR'
        cfs_error_msg: "No existe archivo version ni comando nbgetconfig"