---
- block:
    - name: Obtener IP Robótica o Datos para definir el sufijo del cliente
      set_fact:
        nbkchpiprbt: >-
          {{
            (ansible_all_ipv4_addresses | default([]))
            | select('regex', '^172[.](10|11|13)[.]')
            | list
          }}

    - name: Asignar cfs_status si el equipo no tiene IP Robótica
      set_fact:
        cfs_status: 'ERROR'
        cfs_error_msg: "El servidor no cuenta con IP Robótica en los segmentos requeridos (172.10.x.x, 172.11.x.x, 172.13.x.x)"
      when: nbkchpiprbt | length == 0

    - name: Definir sufijo de cliente (_nbu)
      set_fact:
        nbcltsfx: "{{ ansible_hostname ~ '_nbu' }}"
      when: nbkchpiprbt | length > 0

    - name: Tercera condición, validar IP Robótica
      set_fact:
        run_playbook: |
          {% if (nbkchpiprbt | length > 0) and (nbkchpiprbt[0].startswith('172.10.') or nbkchpiprbt[0].startswith('172.11.') or nbkchpiprbt[0].startswith('172.13.')) %}
          ['s7bckfilehosts','s8prgfilehosts','s9addnbhf{{ nbmsrv }}','s10bcknbbpconf','s11addnbmsbpconf{{ nbmsrv }}']
          {% else %}
          []
          {% endif %}
      when: nbkchpiprbt | length > 0
    
    - name: Ejecutar tareas NetBackup
      include_tasks: "{{ asbpbact3 }}.yml"
      loop: "{{ run_playbook | from_yaml }}"
      loop_control:
        loop_var: asbpbact3
      when: hostvars[inventory_hostname].get('cfs_status', 'OK') != 'ERROR'

#,'s12chknbcomm']
# - block:
#     - name: Obtener IP Robótica o Datos para definir el sufijo del cliente
#       set_fact:
#         nbkchpiprbt: >-
#           {{
#             ansible_all_ipv4_addresses
#             | select('regex', '^172[.](10|11|13)[.]')
#             | list
#           }}

#     - name: Definir sufijo de cliente (_nbu o sin sufijo)
#       set_fact:
#         nbcltsfx: "{{ ansible_hostname ~ '_nbu' if (nbkchpiprbt | length > 0) else ansible_hostname }}"

#     - name: Tercera condición, validar IP Robótica o IP Servicio
#       set_fact:
#         run_playbook: |
#           {% if (nbkchpiprbt | length > 0) and nbkchpiprbt[0].startswith('172.10') %}
#           ['s7bckfilehosts','s8prgfilehosts','s9addnbhf','s10bcknbbpconf','s11addnbmcbpconf','s12chknbcomm']
#           {% elif (nbkchpiprbt | length > 0) and nbkchpiprbt[0].startswith('172.11') %}
#           ['s7bckfilehosts','s8prgfilehosts','s9addnbhf','s10bcknbbpconf','s11addnbmcbpconf','s12chknbcomm']
#           {% elif (nbkchpiprbt | length > 0) and nbkchpiprbt[0].startswith('172.13') %}
#           ['s7bckfilehosts','s8prgfilehosts','s9addnbhf','s10bcknbbpconf','s11addnbmcbpconf','s12chknbcomm']
#           {% else %}
#           ['s7bckfilehosts','s8prgfilehosts','s9addnbhf','s10bcknbbpconf','s11addnbmcbpconf','s12chknbcomm']
#           {% endif %}
    
#     - name: Ejecutar tareas NetBackup
#       include_tasks: "{{ asbpbact3 }}.yml"
#       loop: "{{ run_playbook | from_yaml }}"
#       loop_control:
#         loop_var: asbpbact3
#       when: hostvars[inventory_hostname].get('cfs_status', 'OK') != 'ERROR'
        