---
- block:
    # - name: Crear copia de respaldo de /etc/hosts
    #   copy:
    #     src: "{{ filehosts }}"
    #     dest: "/etc/hosts.bak_{{ ansible_date_time.date }}_{{ ansible_date_time.epoch }}"
    #     remote_src: true
    #     mode: '0644'

    - name: Eliminar cualquier linea que contenga los hostnames de NetBackup
      lineinfile:
        path: "{{ filehosts }}"
        regexp: '^.*?\b(vxnbucfs|cpdnbumedia3-le|cpdnbumedia6-le|lvprpbckrescc01-cfs|{{ ansible_hostname }}_(nbu|mty|mty1|les|les1|mdf))\b.*$'
        state: absent
  become: true