---
- block:
    - name: Actualizar /etc/hosts para segmento 172.10.x.x
      blockinfile:
        path: "{{ filehosts }}"
        marker: "# {mark} ANSIBLE MANAGED NETBACKUP CFS 172.10"
        block: |
          172.10.101.15 vxnbumdf
          172.10.117.131 cbnbumedia6-le
          172.10.119.21 cpdnbumedia4-le
          172.10.108.69 lopahcrespmx03_mdf
          {{ nbkchpiprbt[0] }} {{ nbcltsfx }}
      when: 
        - nbkchpiprbt | length > 0
        - nbkchpiprbt[0].startswith('172.10.')
      register: hosts_update_17210

    - name: Consolidar estado de hosts_update
      set_fact:
        hosts_update:
          changed: >-
            {{
              (hosts_update_17210.changed | default(false))
            }}
  become: true
