---
towerbaseurlapi: "http://192.168.49.2:30203/api/v2/job_templates/"
idplantilla: "21"
accion: "Renovar password root"
towertoken: "{{ lookup('env','TOWER_OAUTH_TOKEN') }}"
retries: 150
delay: 2
fechahoraactual: "{{ now(fmt='%d-%m-%Y %H:%M:%S') }}"
nombreservidor: "{{ inventory_hostname.split('.')[0] }}"
direccionip: "{{ hostvars[inventory_hostname]['ipaddress'] }}"
grado: "{{ hostvars[inventory_hostname]['tier'] }}"
entorno: "{{ hostvars[inventory_hostname]['entorno'] }}"
plataforma: "{{ ansible_system | lower }}"
sistemaos: "{{ ansible_os_family | lower }}"
sistemaosv: "{{ ansible_distribution_major_version }}"
sistemaosvaix: "{{ ansible_distribution_version.split('.')[0:2] | join('.') }}"
directoriologs: "/var/opt/ansible"
directoriocandado: "{{ directoriologs }}/candado"
servidorseguro: "lcmasb4gmx99.bvm.bluecare.kyndryl.net"
servidorautomation: "lcmasb4gmx99.bvm.bluecare.kyndryl.net"
superuser: "root"
clavealeatoria: "</dev/urandom tr -dc 'A-Za-z0-9!@#$%^&*()' | head -c 14; echo"
tipoexpiracion: "horas"
tiempoexpiracionhrs: 72
tiempoexpiraciondia: 3