---
- name: PlayBook - Prestano de root temporal
  block:
    - set_fact:
        runplaybook: |
          {% if actions == 'Barredora prestamo de password roots' and servidorautomation in ansible_play_hosts %}
          ['s0chkbarradorasu']
          {% elif actions == 'Barredora prestamo de password roots' and servidorautomation not in ansible_play_hosts %}
          ['s91msgprespwdsu']
          {% elif actions in ['Renovar password root'] %}
          ['s3genpwdrdmsu','s4setpwd{{ plataforma }}su','s9genreppwdsu']
          {% else %}
          ['No selecciono ninguna tarea', 'No_selecciono_ninguna_tarea']
          {% endif %}
    
    - name: Condicion de tareas borrar password root
      become: true
      assert:
        that:
          - "'No_selecciono_ninguna_tarea' not in runplaybook"
        fail_msg: "runplaybook"
        success_msg: "Ha seleccionado la tarea: {{ actions }}"
      run_once: true
      delegate_to: localhost
    
    - name: Validar condicion para borrar archivos json exprirados 
      include_tasks: "{{ asbpbact }}.yml"
      loop: "{{ runplaybook }}"
      loop_control:
        loop_var: asbpbact

    # - name: Definir enrutamiento según existencia de candados expirados
    #   set_fact:
    #     runplaybook: |
    #       {% if (archjsonexpdel | length > 0) %}
    #       ['s9genreppwdsu']
    #       {% else %}
    #       ['s90msgprespwdsu']
    #       {% endif %}

    # - name: Validar condicion para borrar archivos json exprirados 
    #   include_tasks: "{{ asbpbact2 }}.yml"
    #   loop: "{{ runplaybook }}"
    #   loop_control:
    #     loop_var: asbpbact2