---
- block:
    - name: Obtener fecha actual del servidor
      set_fact:
        fechactualphumana: "{{ now(fmt='%d-%m-%Y') }}"

    - name: Obtener fecha actual del servidor
      set_fact:
        fechactualphumana: "{{ now(fmt='%d-%m-%Y') }}"

    - name: Buscar archivos json que contienen la fecha actual de expiracion
      become: true
      shell: "grep -rl {{ fechactualphumana }} /var/opt/ansible/candado"
      register: archjsonexp
      failed_when: archjsonexp.rc > 1
      changed_when: false

    - name: Buscar equipos en archivos json que contienen la fecha actual de expiracion
      become: true
      shell: "grep -rlE {{ fechactualphumana }} | sort -rn | uniq | sed 's|.json|.*|g' | xargs"
      args:
        chdir: /var/opt/ansible/candado
      register: archjsonhost
      failed_when: archjsonhost.rc > 1
      changed_when: false

    - set_fact:
        runplaybook: |
          {% if archjsonexp.rc == 0 %}
          ['s1borrajsonexp']
          {% else %}
          ['s90msgnoarchjson']
          {% endif %}

    - name: Ejecutar tareas Tickt Helix y Generar password root aleatoreo unificado  
      include_tasks: "{{ asbpbact }}.yml"
      loop: "{{ runplaybook1 }}"
      loop_control:
        loop_var: asbpbact1

    # - name: Lista de archivos json a borrar
    #   set_fact:
    #     archjsonexpdel: "{{ archjsonexp.stdout_lines }}"

    # - name: Lista de archivos json a borrar
    #   set_fact:
    #     archjsonexpdel: "{{ archjsonexp.stdout_lines }}"

    # - name: Eliminar archivos encontrados
    #   become: true
    #   file:
    #     path: "{{ item }}"
    #     state: absent
    #   loop: "{{ archjsonexpdel }}"
    #   when: archjsonexpdel | length > 0

