---
- block:
    - name: Dividir contraseña
      set_fact:
        clave_parte_a: "{{ claveplana[:((claveplana | length) // 2)] }}"
        clave_parte_b: "{{ claveplana[((claveplana | length) // 2):] }}"

    - name: Enviar correo Parte A
      mail:
        host: 192.168.0.245
        port: 25
        from: "AUTOMATION CENTER <automationcenter.io.mx@company-x.ldn>"
        subject: "[Renovación Automatica de Roots] Parte A de Credencial Root"
#        to: "{{ to }}"
        cc: "{{ emailcc }}"
        subtype: html
        charset: utf8
        body: "{{ lookup('template', 'entrega_de_root_lado_a.html.j2') }}"
      delegate_to: "{{ servidorautomation }}"

    - name: Esperar 2 minutos antes de enviar Correo B
      pause:
        seconds: 5

    - name: Enviar correo Parte B
      mail:
        host: 192.168.0.245
        port: 25
        from: "AUTOMATION CENTER <automationcenter.io.mx@company-x.ldn>"
        subject: "[Renovación Automatica de Roots] Parte B de Credencial Root"
#        to: "{{ to }}"
        cc: "{{ emailcc }}"
        subtype: html
        charset: utf8
        body: "{{ lookup('template', 'entrega_de_root_lado_b.html.j2') }}"
      delegate_to: "{{ servidorautomation }}"
