---
- block:
    - name: Ejecutar plantilla renovacion de roots 
      uri:
        url: "{{ towerbaseurlapi }}/{{ idplantilla }}/launch/"
        validate_certs: false
        force_basic_auth: true
        status_code: [200, 201, 204, 400]
        method: POST
        headers:
          Authorization: "Bearer {{ tower_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          inventory: 2
          credentials: [4,8]
          limit: "{{ archjsonhtsdel }}"
          extra_vars:
            actions: "{{ accion }}"
      register: lanzar_plantilla
  delegate_to: localhost
  run_once: false