---
- block:
    - name: Ejecutar plantilla renovacion de roots 
      uri:
        url: "{{ towerbaseurlapi }}/{{ idplantilla }}/launch/"
        validate_certs: false
        force_basic_auth: true
        status_code: [200, 201, 204, 400]
        method: POST
        headers:
          Authorization: "Bearer {{ towertoken }}"
          Content-Type: "application/json"
        body_format: json
        body:
          inventory: 2
          credentials: [4,8]
          limit: "{{ archjsonhtsdel }}"
          extra_vars:
            actions: "{{ accion }}"
      register: lanzar_plantilla

    - name: Valida la ejecucion de la plantilla renovacio de roots
      uri:
        url: "{{lanzar_plantilla.location}}"
        validate_certs: no
        force_basic_auth: yes
        method: GET
        headers:
          Authorization: "Bearer {{ towertoken }}"
        status_code: 200, 201, 204
      register: trabajos_aap
      until: trabajos_aap.json.status == 'successful' or trabajos_aap.json.status == 'failed' or trabajos_aap.json.status == 'canceled' or trabajos_aap.json.status == 'error' 
      failed_when: trabajos_aap.json.status == 'failed' or trabajos_aap.json.status == 'canceled'
      delay: "{{ delay }}"
      retries: "{{ retries }}"
  ignore_errors: true
  delegate_to: localhost