---
- block:
    - name: No aplica borrado de archivos json roots
      set_fact:
        borrararchroot: 'PREVENTIVO'
        borrararchrootmsg: "[PREVENTIVO] ⚠️ Para la opcion -Barredora prestamo de password roots- solo ingrese en el limite el servidor {{ servidorautomation.split('.')[0] }}.*"

    - name: Notificar mensaje de borrado de archivos json roots
      debug:
        msg: "{{ borrararchrootmsg }}"